### ISSUE TITLE
Create Survey Questions 

### ISSUE THREAD

**Issue by Nagehan1** [PakizeBozkurt/hugsforbugs#26]
## Story
As a developer

I Want to prepare a feedback form for external and internal stakeholders

So That we can improve our project.

Acceptance Criteria
A list of questions to be shared with internal or external stakeholders.

**Comment by Nagehan1** [comment]
Here is our survey link.
https://docs.google.com/forms/d/1OZFnvDrSxY7NaOY_VPaf98Sl9IcCMoCmgAP06xgCq-A/edit

**Comment by PakizeBozkurt** [comment]
This is the our app with [Figma design](https://www.figma.com/proto/t95cH6bzAN7sjw45vg7rQ4/Study-Buddies?node-id=1%3A5&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A5)
