### ISSUE TITLE
Refactor: Make backend more DRY

### ISSUE THREAD

**Issue by RainbowGiantSquid** [PakizeBozkurt/hugsforbugs#36]
## Story
This is just for the code improvements

## Acceptance Criteria

1. [Make it more DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

## Checklist:

- [ ] I have defined the user story
- [ ] I have defined some acceptance criteria
- [ ] I have included any implementation notes
- [ ] I have included all relevant links

**Comment by PakizeBozkurt** [comment]
👍
