### ISSUE TITLE
Database schema - update Render DB to the newest schema

### ISSUE THREAD

**Issue by RainbowGiantSquid** [PakizeBozkurt/hugsforbugs#43]
## Story
want to see topic

## Acceptance Criteria
the db deployed to Render is the same as in code (add topic column)

## Checklist:
- [ ] I have defined the user story
- [ ] I have defined some acceptance criteria
- [ ] I have included any implementation notes
- [ ] I have included all relevant links

**Comment by PakizeBozkurt** [comment]
It's already have it.
